# Generated by Django 5.0.6 on 2024-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='end_value',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='start_value',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='value_policy',
            field=models.CharField(blank=True, default='value', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='researchquestion',
            name='aggregation_function',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchquestion',
            name='aggregation_policy',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchquestion',
            name='session_policy',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='researchquestion',
            name='visualization_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
