# Generated by Django 5.0.6 on 2024-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_eventgroup_research_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquestion',
            name='measurement',
            field=models.CharField(default='gameplay', max_length=250),
        ),
    ]
