# Generated by Django 5.0.6 on 2024-06-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_researchquestion_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='accessor',
            field=models.CharField(blank=True, default='value', max_length=250),
        ),
    ]
