# Generated by Django 5.0.6 on 2024-06-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_eventgroup_accessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='label',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
