# Generated by Django 5.0.6 on 2024-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='accessor',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
