# Generated by Django 5.0.6 on 2024-06-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_eventgroup_accessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='label',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
