# Generated by Django 5.0.6 on 2024-06-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_eventgroup_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquestion',
            name='label_for_time',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='researchquestion',
            name='time_between',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='value_policy',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
